version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    links:
      - db:5432
    container_name: api
    build: ./docker/api
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./code:/usr/src/server
volumes:
  db:
    driver: local
